# Generated by Django 5.2.8 on 2025-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
